/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.jresendiz27.muxedo

import groovy.util.logging.Log
import io.vertx.core.Vertx
import io.vertx.core.http.HttpServer
import io.vertx.ext.web.Router
import io.vertx.ext.web.RoutingContext

@Log
class MuxedoServer {
    static void main(String[] args) {
        Vertx vertx = Vertx.vertx()
        HttpServer server = vertx.createHttpServer();
        Map routesDefinition = [
                paths          : [[
                                          path             : '/uri/:param1/:param2',
                                          methods          : ['POST', 'GET', 'PUT'],
                                          uriParams        : [
                                                  [
                                                          name: 'param1',
                                                          type: 'Integer'
                                                  ],
                                          ],
                                          expectedResponses: [
                                                  [
                                                          code           : 200,
                                                          expectedHeaders: [],
                                                          responseWeight : 50,
                                                          body           : "This is a mocked body 1",
                                                          responseHeaders: [
                                                                  'Content-Type': 'text/plain'
                                                          ]
                                                  ],
                                                  [
                                                          code           : 403,
                                                          expectedHeaders: [],
                                                          responseWeight : 50,
                                                          body           : "This is a mocked body 2",
                                                          responseHeaders: [
                                                                  'Content-Type': 'text/plain22222'
                                                          ]
                                                  ]
                                          ]

                                  ],
                                  [
                                          path             : '/hello/world',
                                          methods          : ['GET', 'PUT'],
                                          expectedResponses: [
                                                  [
                                                          code           : 200,
                                                          expectedHeaders: [],
                                                          body           : "This is a mocked body 1",
                                                          responseHeaders: [
                                                                  'Content-Type': 'text/plain'
                                                          ]
                                                  ]
                                          ],
                                          errorHandler     : [
                                                  code           : 500,
                                                  responseHeaders: [
                                                          'Content-Type': 'text/plain'
                                                  ],
                                                  showErrors     : true
                                          ]
                                  ]],
                errorHandler   : [
                        code           : 500,
                        responseHeaders: [
                                'Content-Type': 'application/json'
                        ],
                        showErrors     : true
                ],
                notFoundHandler: [
                        responseHeaders: [
                                'Content-Type': 'application/json'
                        ],
                        showErrors     : true
                ]
        ]
        Router router = new RouterFactory(vertx).create(routesDefinition)
        router.errorHandler(500, { RoutingContext handler ->
            log.info("Exception: ${handler.failure()}")
            log.info("Exception: ${handler.failure()}")
            log.info("Exception: ${handler.failure()}")
            log.info("Exception: ${handler.failure()}")
            handler.failure().printStackTrace()
            if (!handler.response().headWritten()) {
                handler.response().end("Exception: ${handler.failure()}")
            }
        })
        vertx.exceptionHandler({ handler ->
            handler.printStackTrace()
        })
        server.requestHandler(router).listen(8081)
    }
}