/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.jresendiz27.muxedo

import spock.lang.Specification

class LibraryTest extends Specification {
    def "someLibraryMethod returns true"() {
        true
    }
}
